package skills

import (
	"context"
	"fmt"
	"strings"

	forward "github.com/forwardnetworks/forward-go-sdk"

	"github.com/forwardnetworks/fwdctl/fwd"
)

// Claimant is a synthetic node connection that claims an uplink: the node's uplinkPort or gatewayPort is the port, or (a subinterface) the uplink is its parent port and the VLAN agrees.
type Claimant struct {
	Kind    string // internet, intranet, l3vpn, l2vpn, adjacent-network
	Node    string
	Uplink  string // "device port"
	Gateway string // "device port", empty when none
	VLAN    *int
	VRF     string
	Source  string // manual (a stored connection) or query (generated by the node's NQE query)

	up, gw portRef
}

type portRef struct{ Device, Port string }

// Map is the claimed_by shape of the skill's evidence.
func (c Claimant) Map() map[string]any {
	m := map[string]any{"kind": c.Kind, "node": c.Node, "uplink": c.Uplink, "gateway": nilIfEmpty(c.Gateway), "vrf": nilIfEmpty(c.VRF), "source": c.Source}
	if c.VLAN != nil {
		m["vlan"] = *c.VLAN
	} else {
		m["vlan"] = nil
	}
	return m
}

// ClaimIndex is every connection of every synthetic node the network has, and the node kinds that could not be read.
type ClaimIndex struct {
	Conns    []Claimant
	Nodes    int
	Unread   []string // "<kind>: why"
	ReadKind int
}

type claimKind struct {
	name string
	kind forward.SyntheticNodeKind
}

// loadClaims reads the internet node, intranet nodes, L3 VPNs, L2 VPNs and adjacent networks with their stored connections and the connections their NQE queries generated.
// A kind this Forward does not serve is recorded in Unread, never an error.
func loadClaims(ctx context.Context, s *fwd.Session, networkID string) (*ClaimIndex, error) {
	ci := &ClaimIndex{}
	add := func(kind string, n forward.SyntheticNode) {
		ci.Nodes++
		for _, c := range n.Connections {
			ci.Conns = append(ci.Conns, newClaimant(kind, n.Name, "manual", c))
		}
		if n.QueryResult != nil {
			for _, c := range n.QueryResult.Connections {
				ci.Conns = append(ci.Conns, newClaimant(kind, n.Name, "query", c))
			}
		}
	}
	if n, err := s.InternetNode(ctx, networkID); err != nil {
		ci.Unread = append(ci.Unread, "internet node: "+err.Error())
	} else {
		ci.ReadKind++
		if n != nil {
			add("internet", *n)
		}
	}
	for _, k := range []claimKind{{"intranet", forward.SyntheticIntranet}, {"l3vpn", forward.SyntheticL3VPN}, {"l2vpn", forward.SyntheticL2VPN}, {"adjacent-network", forward.SyntheticAdjacentNetwork}} {
		nodes, err := s.SyntheticNodes(ctx, networkID, k.kind)
		if err != nil {
			ci.Unread = append(ci.Unread, k.name+": "+err.Error())
			continue
		}
		ci.ReadKind++
		for _, n := range nodes {
			add(k.name, n)
		}
	}
	return ci, nil
}

func newClaimant(kind, node, source string, c forward.SyntheticNodeConn) Claimant {
	x := Claimant{Kind: kind, Node: node, Source: source, VRF: c.VRF, VLAN: c.Vlan,
		up: portRef{c.UplinkPort.Device, c.UplinkPort.Port}, Uplink: c.UplinkPort.Device + " " + c.UplinkPort.Port}
	if c.GatewayPort != nil && (c.GatewayPort.Device != "" || c.GatewayPort.Port != "") {
		x.gw = portRef{c.GatewayPort.Device, c.GatewayPort.Port}
		x.Gateway = c.GatewayPort.Device + " " + c.GatewayPort.Port
	}
	return x
}

// claims says whether the connection claims the (sub)interface: its uplink or gateway is that port, or the port is a subinterface "<uplink>.<vlan>" of the connection's uplink
// and the connection's VLAN is that number.
func (c Claimant) claims(device, port string) bool {
	if (c.up.Device == device && c.up.Port == port) || (c.gw.Device == device && c.gw.Port != "" && c.gw.Port == port) {
		return true
	}
	if v, ok := subVLAN(port); ok && c.VLAN != nil && *c.VLAN == v && c.up.Device == device && c.up.Port == port[:strings.LastIndex(port, ".")] {
		return true
	}
	return false
}

// claimsOf lists the nodes that claim the (sub)interface, one entry per node (the first matching connection), in the order the nodes were read.
func (ci *ClaimIndex) claimsOf(device, port string) []Claimant {
	var out []Claimant
	seen := map[string]bool{}
	for _, c := range ci.Conns {
		if c.claims(device, port) && !seen[c.Kind+"/"+c.Node] {
			seen[c.Kind+"/"+c.Node] = true
			out = append(out, c)
		}
	}
	return out
}

// ClaimsOf is claimsOf for callers outside the package.
func (ci *ClaimIndex) ClaimsOf(device, port string) []Claimant { return ci.claimsOf(device, port) }

func (c Claimant) String() string {
	return fmt.Sprintf("%s %s (%s)", c.Kind, c.Node, c.Source)
}
